
CC=g++
CFLAGS=-c  $(shell pkg-config fuse --cflags)
LDFLAGS=$(shell pkg-config fuse --libs)
SOURCES=main.cpp File.cpp Disk.cpp File.h Disk.h common.h
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=profuse

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@
