CC = g++
CPPFLAGS += -Wall -O2 -g -fexceptions
LDFLAGS += -L/usr/local/lib -lfuse

newfs_pascal: \
 newfs_pascal.o \
 Date.o \
 File.o \
 ../Exception.o \
 ../BlockDevice.o \
 ../BlockCache.o \
 ../DiskCopy42Image.o \
 ../RawDevice.o \
 ../MappedFile.o \
 ../Buffer.o 
 

fileman : \
 FileMan.o \
 Date.o \
 File.o \
 ../Exception.o \
 ../BlockDevice.o \
 ../BlockCache.o \
 ../DiskCopy42Image.o \
 ../RawDevice.o \
 ../MappedFile.o \
 ../Buffer.o  

 
profuse_pascal : \
 profuse_pascal.o \
 profuse_pascal_ops.o \
 Date.o \
 File.o \
 ../Exception.o \
 ../BlockDevice.o \
 ../BlockCache.o \
 ../DiskCopy42Image.o \
 ../RawDevice.o \
 ../MappedFile.o \
 ../Buffer.o  