CC = g++
CPPFLAGS += -Wall -O2 -g

newfs_pascal: \
 newfs_pascal.o \
 Date.o \
 File.o \
 ../Exception.o \
 ../BlockDevice.o \
 ../BlockCache.o \
 ../DiskCopy42Image.o \
 ../RawDevice.o \
 ../MappedFile.o \
 ../Buffer.o \
 
 
 
